[options]
admin_passwd = admin@123
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter= .*
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/enterprise/odoo/addons,/mnt/extra-addons

